check apply_planning_scene before creating collision-object-publisher/*ci*
jsk-ros-pkg/jsk_pr2eus pull request #446
Opened 2020-10-28 11:44 UTC by k-okada

this should avoid https://github.com/jsk-ros-pkg/jsk_robot/issues/1264 problem

2020-11-18 07:41 UTC, knorth55 approved these changes

2020-11-18 07:42 UTC, knorth55 requested changes

2020-11-18 07:42 UTC, knorth55 commented on pr2eus_moveit/euslisp/collision-object-publisher.l
> +	       (service-wait-time -1))
please remove tab
```suggestion
               (service-wait-time -1))
```

2020-11-20 14:33 UTC, knorth55 requested changes

2020-11-20 14:33 UTC, knorth55 commented on pr2eus_moveit/euslisp/collision-object-publisher.l
> +	 (return-from :wipe-all-object t))
please remove tabs.

```suggestion
         (ros::ros-warn ";; collision-object-publisher ~A service could not found, so skipping calling service" servicename)
         (return-from :wipe-all-object t))
```

2020-11-20 14:33 UTC, knorth55 commented on pr2eus_moveit/euslisp/collision-object-publisher.l
> +	 (return-from :wipe-all-attached-object t))
please remove tabs.

```suggestion
         (ros::ros-warn ";; collision-object-publisher ~A service could not found, so skipping calling service" servicename)
         (return-from :wipe-all-attached-object t))
```

2020-11-20 14:33 UTC, knorth55 commented on pr2eus_moveit/euslisp/collision-object-publisher.l
> +	(return-from :delete-object-by-msg))
please remove tabs.

```suggestion
        (ros::ros-warn ";; collision-object-publisher ~A service could not found, so skipping calling service" servicename)
        (return-from :delete-object-by-msg))
```

2021-07-21 01:15 UTC, k-okada commented on pr2eus_moveit/euslisp/collision-object-publisher.l
> +	       (service-wait-time -1))
thank you, removed all tabs

2021-11-22 07:55 UTC, merged